### ISSUE TITLE
keyterms.sgrank() - python2 v. python3 discrepancies

### ISSUE THREAD

**Issue by schmod** [chartbeat-labs/textacy#125]
I've observed that `textacy.keyterms.sgrank()` can produce different results in Python 2 and Python 3.  

In my specific test-cases, I'm observing that `sgrank` returns (considerably) more key terms in Python 2 compared to Python 3, but I believe that this pattern is specific to my case.  

---

I've stepped through `sgrank()` with a debugger, and observed that Python 2 and 3 diverge in [this block](https://github.com/chartbeat-labs/textacy/blob/8ec807970e5464bf2559a2d5042ea5a4cce8b52e/textacy/keyterms.py#L27): 

```python
n_prefilter_kts = max(3 * n_keyterms, 100)
term_text_counts = Counter(term[0] for term in terms)
if idf:
    mod_tfidfs = {
        term: count * idf.get(term, 1) if ' ' not in term else count
        for term, count in term_text_counts.items()}
    terms_set = {
        term for term, _
        in sorted(mod_tfidfs.items(), key=itemgetter(1), reverse=True)[:n_prefilter_kts]}
else:
    terms_set = {term for term, _ in term_text_counts.most_common(n_prefilter_kts)}
terms = [term for term in terms if term[0] in terms_set]
```

The specific line that appears to be problematic is:

```python
terms_set = {term for term, _ in term_text_counts.most_common(n_prefilter_kts)}
```

Python's [documentation](https://docs.python.org/3/library/collections.html#collections.Counter.most_common) for `Counter#most_common([n])` is as follows (emphasis mine):

> Return a list of the n most common elements and their counts from the most common to the least. If n is omitted or None, most_common() returns all elements in the counter. **Elements with equal counts are ordered arbitrarily**

Obviously, this last clause presents a problem for us.  The underlying implementation of `Counter` appears to have diverged between Python 2 and 3, such that ties are now broken in an arbitrarily-different fashion (the behavior _does_ appear to be consistent within the same version of Python, although the documentation makes clear that this is not an explicit guarantee).  

In a short document, `term_text_counts` will typically contain roughly a dozen terms that occur 2-3+ times, and several hundred terms that only appear once.  The current naive sampling of these several hundred terms appears to have a significant effect, and likely introduces a bias toward terms that appear near the beginning/end of the document, given the underlying implementation of `Counter#most_common()`.

---

I don't have a proposed solution to this problem (nor do I have the background necessary to comment on the appropriateness of `sgrank()`'s current prefiltering algorithm) -- just wanted to ensure that this strange behavior was known and documented somewhere.

Additionally, I did not follow the debugger through the remainder of `sgrank()` -- it's possible that there are other Python2/3 discrepancies further down the line.

**Comment by bdewilde** [comment]
Hey @schmod , thanks a ton for your detailed detective-work! This is interesting...

As far as I understand, SGRank is better suited to longer texts; in fact, the concept of a "keyterm" in very short texts is a bit strange, since every (non-stop) word could be considered "key". The issue you've noticed may arise from the fact that you only have a few readily identifiable keyterms per text, and everything else is in a long, ambiguously key tail. One option is to limit the number of terms via the `n_keyterms` param; its default is 10, but you may want fewer. Another is to use a simpler keyterm detection method, e.g. `textrank()`, ranking words by tf-idf, or just taking the nouns.

So... I'm not sure there's a clear "solution" to this issue. One thing I can do, though, is add a note to the `sgrank()` docstring mentioning that it is better suited to longer texts. Does that seem reasonable to you?
