### ISSUE TITLE
Truecasing words

### ISSUE THREAD

**Issue by chssch** [chartbeat-labs/textacy#15]
I read in https://github.com/chartbeat-labs/textacy/blob/master/README.rst about truecasing words, but can't find it in the code. Do you have any hints?

P.S. I use and love spacy already. Just went through the textacy code, it's an excellent abstraction for a lot different use cases. Great work. 👍

**Comment by bdewilde** [comment]
Hi @chssch, thanks for your kind words! Glad that the code makes sense to people who aren't me. :grin:

The function you're probably looking for is [`textacy.spacy_utils.normalized_str`](https://github.com/chartbeat-labs/textacy/blob/master/textacy/spacy_utils.py#L73), which takes a spaCy token and returns its text as-is if it's a proper noun or acronyms, and lemmatized text otherwise. Not _great_, but it does a decent job. I'm very open to ideas and contributions if you have any!

**Comment by chssch** [comment]
Hi @bdewilde, thanks for the hint (and sorry for the late reply).

**Comment by neomafo88** [comment]
`textacy.spacier.utils.get_normalized_text`
