### ISSUE TITLE
AttributeError: module 'textacy' has no attribute 'io'

### ISSUE THREAD

**Issue by mikkokotila** [chartbeat-labs/textacy#152]
Fresh out of the install I get: 

`AttributeError: module 'textacy' has no attribute 'io'
`
I tried both from pypi and git master.

**Comment by mikkokotila** [comment]
Apparently, it should be > 

textacy.fileio.split_record_fields(records, 'text')

**Comment by bdewilde** [comment]
Hi @mikkokotila , that was a refactor from a PR merged in a couple days ago; the docs on GitHub correspond to the code as it is, but there hasn't been a new release published to PyPi with these changes. If you look in the code, you can indeed see that there is an `io` subpackage.

**Comment by bdewilde** [comment]
Hi again, just a bit more context, since I was very brief earlier — was jumping between tasks, my bad!

The documentation (including usage example) for the current release of textacy (v0.5.0) can be found here: https://chartbeat-labs.github.io/textacy/index.html. You can see that it shows `textacy.fileio` and `split_record_fields()` rather than `textacy.io` and `split_records()`. This should be your source of truth if you're not working off the `master` branch, as the latter includes all changes (some _breaking_) since the most recent release.

Sorry about the confusion!
