### ISSUE TITLE
Usage example fails on Supreme Court texts, even with tons of RAM

### ISSUE THREAD

**Issue by suchow** [chartbeat-labs/textacy#154]
I ran the following script, copied from the usage guide with no changes except the data source:

https://gist.github.com/suchow/7f06899bae66b3104a4669cd4d8a118d

And see the following error:

```
(py27) suchow@theano:~$ python topics.py
Traceback (most recent call last):
  File "topics.py", line 9, in <module>
    corpus = textacy.Corpus(u'en', texts=txt_strm, metadatas=meta_strm)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/textacy/corpus.py", line 151, in __init__
    self.add_texts(texts, metadatas=metadatas)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/textacy/corpus.py", line 282, in add_texts
    for spacy_doc, metadata in compat.zip_(spacy_docs, metadatas):
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/spacy/language.py", line 555, in pipe
    for doc in docs:
  File "nn_parser.pyx", line 369, in pipe
  File "cytoolz/itertoolz.pyx", line 1046, in cytoolz.itertoolz.partition_all.__next__ (cytoolz/itertoolz.c:14538)
  File "nn_parser.pyx", line 369, in pipe
  File "cytoolz/itertoolz.pyx", line 1046, in cytoolz.itertoolz.partition_all.__next__ (cytoolz/itertoolz.c:14538)
  File "pipeline.pyx", line 397, in pipe
  File "pipeline.pyx", line 402, in spacy.pipeline.Tagger.predict
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/api.py", line 293, in predict
    X = layer(layer.ops.flatten(seqs_in, pad=pad))
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/resnet.py", line 15, in __call__
    return X + self._layers[0](X)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/api.py", line 55, in predict
    X = layer(X)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)
  File "/home/suchow/anaconda2/envs/py27/lib/python2.7/site-packages/thinc/neural/_classes/convolution.py", line 25, in predict
    return self.ops.seq2col(X, self.nW)
  File "ops.pyx", line 462, in thinc.neural.ops.NumpyOps.seq2col
  File "cymem/cymem.pyx", line 42, in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)
MemoryError: Error assigning 18446744071574251392 bytesError assigning 18446744071574251392 bytesError assigning 18446744071574251392 bytesError assigning 18446744071574251392 bytes
```

The number of bytes it is trying to assign is unrecognizably large, 18446744071574251392, which is something like 2 million terabytes? I'm on a system with 256 GB of RAM, not nearly enough I guess 😉 .

**Comment by bdewilde** [comment]
Hi @suchow , what a delightful error! 😭 

The exception is coming from `cymem` by way of `spacy` — it looks like one of the documents in the Supreme Court corpus is larger than spacy's new neural network parser can effectively handle. Looks similar to https://github.com/explosion/spaCy/issues/1636.

There are a couple things I can think of doing here:

1. Load the English language pipeline and manually apply it to the docs in a try/except block. Print out the size of any text that raises a MemoryError. This would help us confirm our understanding of the error's cause.
2. Split too-large texts into chunks, or just take the first N chars and assume the latter portion is ignore-able (with apologies to the Supreme Court justices).

Sorry about the trouble. Please keep me posted on what you find, and how you work around the problem.

**Comment by suchow** [comment]
Okay, I think I solved this. What I did was to create a truncator that takes in the texts stream generator and a maximum length, and returns a new texts stream generator where the texts are all truncated to the given length:

```
def truncated(text_stream, max_length):
    for text in text_stream:
        yield text[0:max_length]
```

A truncated stream is then passed to `textacy.Corpus`, which I can confirm does solve the problem.

Perhaps you could add a `max_length` parameter to `textacy.Corpus` that does this under the hood.

**Comment by idc9** [comment]
I'm also encountering this problem on some of my own corpuses. @bdewilde thanks for pointing to that issue!


## new spacy exception/argument addressing long documents

It looks like spacy has modified this language class to raise an exception (e.g. see [new __init__](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L130) and [new exception](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L344)). Unfortunately, it's not clear when/how they will address this issue (e.g. see [#1826](https://github.com/explosion/spaCy/issues/1826)).

## fixes for textacy

It might be worthwhile adding functionality to textacy to address this issue until it is fixed in spacy (or permanently since I'm guessing there will always be documents lengths too large for spacy to handle). Some possible solutions:

- simple truncation: add something like @suchow's `truncated`

- process longer documents in smaller chunks then merge them

In many applications the latter is preferable because we really don't want to lose text. I'm facing this issue right now and here are three options I'm considering

1. break up the text in to smaller chunks, process each chunk as a spacy doc, then merge the spacy docs

2. break up the text in to smaller chunks, process each chunk into a textacy doc, then merge the textacy docs

3. modify the `corpus` class to allow for hierarchical corpuses, break up the text in to smaller chunks, process each chunk into a textacy doc, create a sub-corpus combining the textacy docs.

I'm guessing 1/2 are the easiest. 3, however, might be of general interest because some corpuses are naturally hierarchical (e.g. for one supreme court case there might be a majority opinion, a dissenting opinion and a concurring opinion).

**Comment by idc9** [comment]
@bdewilde I implemented your suggestion 1 from above (i.e. load texts one by one into spacy to identify the offending case).  See the attached notebook below (memory explosion notebook.zip).


## results

The memory explosion issue only happens when we create the corpus with [`spacy_lang.pipe()`](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L527) (i.e. [`textacy.Corpus.add_texts()`](https://github.com/chartbeat-labs/textacy/blob/master/textacy/corpus.py#L262)). See example 1 and 4 in the attached Jupyter notebook.  

If we load long texts one by one (i.e. [`textacy.Corpus.add_text`](https://github.com/chartbeat-labs/textacy/blob/master/textacy/corpus.py#L303)) the memory explosion issue does not occur (see examples 2 and 5 from the attached notebook). 

Finally, if we truncate long texts and use `pipe()`/`add_texts()` the memory explosion again does not occur (as @suchow said). See example 3 from the attached notebook.

## issue and possible solution
I'm guessing the word vectors from the larger vocab are what cause the memory error when we use pipe.

This suggests another possible solution for fixing textacy with large documents, namely,
 - add all small documents using `add_texts()`
-  add large large documents one at a time using `add_text()`


## my environment 

- **platform:** darwin
- **python:** 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
- **spacy:** 2.0.5
- **spacy_models:** ['en']
- **textacy:** 0.6.0

## notebook

This zip file contains a Jupyter notebook which demonstrates the behavior discussed above.

[memory explosion notebook.zip](https://github.com/chartbeat-labs/textacy/files/1892088/memory.explosion.notebook.zip)

**Comment by bdewilde** [comment]
Hi @idc9 and @suchow , I think I've found a sufficiently decent workaround for this problem. I've added a `make_doc_from_text_chunks()` function to the `spacier` sub-package that takes a (long) text and a chunk size; splits the text into chunks, then processes those chunks individually with spaCy; and finally combines the chunks' outputs into a single spaCy document. It should use much less RAM on long texts, and still have good runtime performance.

Resolving the underlying problem is more in spaCy's court, although I should note that RAM is frustratingly finite, so there'll always be texts that run up against the limits of our hardware.
