### ISSUE TITLE
extract.ngrams returns wrong bigrams

### ISSUE THREAD

**Issue by ablx** [chartbeat-labs/textacy#157]
Extracting bigrams with filtering punctuation returns not all bigrams.

```
import unittest
from textacy.extract import ngrams as t_ngrams
import spacy

nlp = spacy.load('en')


class TextacyNgrams(unittest.TestCase):

    def test_filter_punct(self):
        ngrams = sorted(t_ngrams(nlp('Java, Python and Ruby foo, bar'), n=2, filter_punct=True))
        print('Produced bigrams {}'.format(ngrams))
        expected = sorted(['Java Python', 'Python and', 'and Ruby', 'Ruby foo', 'foo bar'])
        self.assertListEqual(sorted([t.text for t in ngrams]), expected)


```
## Expected Behavior
For test_filter_punct, I expect: 'Java Python', 'Python and', 'and Ruby', 'Ruby foo', 'foo bar'

## Current Behavior
For test_filter_punct, I get: 'Ruby foo'

## Steps to Reproduce (for bugs)
see snippet above

## Your Environment
{'python': '3.6.4 (default, Dec 25 2017, 14:57:56) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]', 'platform': 'darwin', 'textacy': '0.5.0', 'spacy': '2.0.5', 'spacy_models': ['en']}

**Comment by bdewilde** [comment]
Hi @ablx , I have reproduced your result, and can confirm that it is not a bug. There are two reasons:

1. spacy correctly includes the commas in that text as separate tokens. When iterating over tokens, you get

```
In [5]: for tok in doc:
   ...:     print(tok, tok.pos_)
Java PROPN
, PUNCT
Python PROPN
and CCONJ
Ruby PROPN
foo NOUN
, PUNCT
bar NOUN
```

And when iterating over adjacent token pairs i.e. bigrams, ("Java", ",") and (",", "Python") are rejected bc `filter_punct=True`, while ("Java", "Python") and ("foo", "bar") don't exist because of the commas that separate them.

2. In `textacy.extract.ngrams()`, `filter_stops=True` by default, so bigrams like ("Python", "and") and ("and", "Ruby") are rejected bc "and" is a stopword. You can set this arg to False to change the behavior.

Thus, the only valid bigram is "Ruby foo".

**Comment by ablx** [comment]
Thanks for the detailed explanation - didn't thought about stop words to be honest (as I need to keep them in my application :) )
Thought that "remove stop words" / "remove punctuation" is done before creating bigrams instead 
Didn't read the documentation with enough attention :(
