### ISSUE TITLE
how to get entity types for the list(doc)  after using named_entities( ) method in textacy

### ISSUE THREAD

**Issue by SreejaRoyal** [chartbeat-labs/textacy#161]
## Your Environment

- operating system:
- python version:
- `spacy` version:
- installed `spacy` models:
- `textacy` version:

**Comment by bdewilde** [comment]
Hi @SreejaRoyal , I'll need need much more information if I'm to be helpful with your issue. A description of what you're trying to, and a code sample to replicate the problem, would be a great start.

**Comment by SreejaRoyal** [comment]
Hi, this is my code..... in response I want entity type also, for example ( Donald Trump -> Name, United States ->loc)
>>> import spacy
>>> import textacy
>>> text='''Two weeks ago, I was in Kuwait participating in an I.M.F. seminar for Arab educators.For 30 minutes, we discussed the impact of technology trends on education in the Middle East.And then an Egyptian education official raised his hand and asked if he could ask me a personal question:"I heard Donald Trump say we need to close mosques in the United States," he said with great sorrow.Is that what we want our kids'''
>>> doc=textacy.Doc(text)
>>> ner =  list(textacy.extract.named_entities(doc, drop_determiners=True, exclude_types='numeric'))                                             >>> print (ner)
[Kuwait, I.M.F., Arab, Middle East, Egyptian, question:"I, Donald Trump, mosques, United States]

**Comment by bdewilde** [comment]
Hi @SreejaRoyal , `textacy.extract.named_entities` yields spaCy `Span` objects, which have a [`.label_` attribute](https://spacy.io/api/span#attributes) giving the entity type, if applicable. Here's an example:

```
>>> nes = textacy.extract.named_entities(doc, drop_determiners=True, exclude_types='numeric')
>>> for ne in nes:
...     print(ne, ne.label_)
Kuwait GPE
I.M.F. GPE
Arab NORP
Middle East LOC
Egyptian NORP
Donald Trump PERSON
mosques FAC
United States GPE
```

You didn't say which version of textacy you're using, but I should note that, in the past, entities that had determiners dropped lost their entity labels. This is [fixed in master](https://github.com/chartbeat-labs/textacy/commit/a3cc9cb2bd92295d0b890699b2f4b81ed159e6b2#diff-a0e968e9c14584c380af3f598a42e090), and will be included in the next release.

**Comment by SreejaRoyal** [comment]
Hi bdewilde! thanks for looking into this!
