### ISSUE TITLE
to_bag_of_terms(named_entities=False) doesn't exclude named entities 

### ISSUE THREAD

**Issue by JonathanReeve** [chartbeat-labs/textacy#169]
I'm testing out Textacy using Jane Austen's novel _Persuasion_. Here's the output of `doc.to_bag_of_terms(named_entities=True, as_strings=True)`: 

{'al haines': 1,
 'persuasion': 9,
 '1818': 1,
 'chapter 1': 2,
 'walter elliot': 14,
 'kellynch hall': 26,
 'somersetshire': 5,

Ok great. Now here's the output of `doc.to_bag_of_terms(named_entities=False, as_strings=True)`: 

{'al': 1,
 'haines': 1,
 'persuasion': 8,
 'jane': 1,
 'austen': 1,
 '1818': 1,
 'chapter': 24,
 '1': 3,
 'sir': 149,
 'walter': 140,
 'elliot': 295,
 'kellynch': 73,

It seems it doesn't ignore named entities, it just breaks them into smaller pieces. The names are still there ("jane," "austen"). 

## Expected Behavior
The algorithm should exclude parts of named entities in addition to complete ones. 

## Current Behavior
I think it's excluding named entities, but not excluding their parts. 

## Possible Solution
Exclude all words which are parts of named entities, in addition to complete ones. 

## Steps to Reproduce (for bugs)
Run the commands listed above. 

- operating system: Linux
- python version: 3
- `spacy` version: latest
- installed `spacy` models: english (large)
- `textacy` version: latest

**Comment by bdewilde** [comment]
Hey @JonathanReeve , the issue here is that there's also an `ngrams` argument to `Doc.to_bag_of_terms()`, and by default it includes uni-, bi-, and tri-grams. In the case that both ngrams and named entities are requested, the code checks for exact duplicates to prevent double-counting the same thing, but it doesn't exclude ngrams that constitute parts of named entities. In the case that ngrams are requested but named entities are *not*, the code doesn't check ngrams against entities at all. I think there's a case to be made for, as before, excluding ngrams that coincide exactly with named entities, but not for partial matches.

I feel pretty strongly that excluding partial entities would be undesirable behavior, but I'd love to hear the counter argument. Thanks for the report, hope we can find a mutually agreeable solution!

**Comment by JonathanReeve** [comment]
Hey thanks for your help on this. It's probably just that I don't understand how this is working, so apologies in advance. 

I'm not quite sure what you mean by ngrams—do you mean ngrams where n>1? I've tried excluding n>1 grams, but I'm still seeing the same issue. Is this the desired behavior? 

```
>>>bag = doc.to_bag_of_terms(named_entities=False, ngrams=(1), as_strings=True)
>>>bag
{'al': 1,
 'haines': 1,
 'persuasion': 8,
 'jane': 1,
 'austen': 1,
 '1818': 1,
 'chapter': 24,
 '1': 3,
 'sir': 149,
 'walter': 140,
 'elliot': 295,
 'kellynch': 73,
 'hall': 28,
 'somersetshire': 4,
```

FWIW, I can roll my own unigram solution with something like this: 

```
def getBagOfWords(text): 
    """ Gets a bag of words representation of a text, 
    ignoring named entities, and lemmatizing along the way."""
    doc = textacy.Doc(text, lang='en')
    wordDict = {}
    for word in doc: 
        if word.ent_type == 0:
            if word in wordDict: 
                wordDict[word.lemma_] += 1
            else: 
                wordDict[word.lemma_] = 1
    return wordDict
```
But it'd be great if there were a way to do this with textacy. At the very least, I'd like to be able to get a bag of words that didn't have any named entities or parts of named entities. I'm finding it hard to imagine how it'd be good to exclude "Jane Austen" but include that same name, as separate words, "Jane" and "Austen." 

As one example, let's say I'm trying to topic model a novel. The top words in a topic are mostly names (Elizabeth, Wentworth, etc.). If I want a representation of the subjects discussed in the novel that aren't characters (other nouns, verbs, etc.), I'd like to use a bag of words that doesn't contain named entities.
