### ISSUE TITLE
Cannot disable a space module

### ISSUE THREAD

**Issue by brtknr** [chartbeat-labs/textacy#182]
Not sure whether this is an intended feature but if I do the following:

```python
lang = 'en'
corpus = textacy.Corpus(lang)
for item in ['ner', 'parser']:
    if item in corpus.spacy_lang.pipe_names:
        corpus.spacy_lang.remove_pipe(item)
```
 
I get an error saying parser doesn't exist when I proceed to add some text to the corpus using `corpus.add_text(doc)`.

I would expect textacy to behave normally and simply not allow features that require parsing, not try to stop me from adding text in the first place...

**Comment by bdewilde** [comment]
Hi @brtknr , I'm _pretty sure_ I fixed this just yesterday, and the fix is in master. See here: https://github.com/chartbeat-labs/textacy/commit/c78a4e1d1ec647a1f1d3988e007a44671d05fae0

If that doesn't resolve your problem, please re-open the issue and give a bit more detail to point me in the right direction.

**Comment by brtknr** [comment]
Thanks, just what I wanted! :)
