### ISSUE TITLE
Question: NER example

### ISSUE THREAD

**Issue by adrianR2** [chartbeat-labs/textacy#20]
Hello, I want to perform NER(and other IE) and display the result. I tried

```
>>> example=""" Opportunities New Brunswick chair Roxanne Fairweather was on hand for the announcement this morning at the Clean Harbours office on Whitebone Way in the McAllister Industrial Park."""
>>> print example
 Opportunities New Brunswick chair Roxanne Fairweather was on hand for the announcement this morning at the Clean Harbours office on Whitebone Way in the McAllister Industrial Park.

>>> ner=textacy.extract.named_entities(content, good_ne_types=None, bad_ne_types=None, min_freq=1, drop_determiners=True)
```

```
>>> print(i for i in ner)
<generator object <genexpr> at 0x080D37B0>

>>> print(list(i for i in ner))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <genexpr>
  File "textacy\extract.py", line 158, in named_entities
    nes = doc.ents
AttributeError: 'str' object has no attribute 'ents'

>>> [i for i in ner]
[]
```

May I see an  actual usage example please? (I barely know how to use Python)
Thanks. Adrian.

**Comment by bdewilde** [comment]
Hi @adrianR2, `textacy.extract.named_entities()` is a generator function. If you want to iterate once over its results, simply do `for ne in named_entities(content): print(ne)`; if you want to save its results in a data structure that lasts beyond one iteration, do something like `list(named_entities(content))`. In your print function, you iterated over the results as a generator, so it printed that object rather than the items contained within it.

**Comment by adrianR2** [comment]
Thanks Burton, `named_entities` it is not recognized:
```
>>> for ne in named_entities(content): print(ne)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'named_entities' is not defined
>>>
```

**Comment by bdewilde** [comment]
You need to call the function as it's named in your working namespace... For example:

```
from textacy.extract import named_entities
for ne in named_entities(content):
...
```

or

```
import textacy
for ne in textacy.extract.named_entities(content):
...
```

**Comment by adrianR2** [comment]
Thanks. It still does not work: 

```
>>> import textacy
C:\Anaconda2\lib\site-packages\fuzzywuzzy-0.10.0-py2.7.egg\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this war
ning
>>> from textacy.extract import named_entities
>>> text=""" Opportunities New Brunswick chair Roxanne Fairweather was on hand for the announcement this morning at the Clean Harbours office on Whitebone Way in the McAllister Ind
ustrial Park."""
>>> for ne in named_entities(text): print(ne)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textacy\extract.py", line 158, in named_entities
    nes = doc.ents
AttributeError: 'str' object has no attribute 'ents'
```

What I did wrong in the above?

**Comment by bdewilde** [comment]
Hey, please read the documentation attached to all functions. The `named_entities()` function expects as input a spacy document, not a string of raw text.

**Comment by adrianR2** [comment]
Right, sorry. I looked at
http://textacy.readthedocs.io/en/latest/api_reference.html
and
https://media.readthedocs.org/pdf/textacy/latest/textacy.pdf

and I could not find how to process a text with spaCy while in textacy.
Should I launch spacy first, process text with `nlp()`, save it to file, and then launch textacy, read the saved file and process with `named_entities()`?

**Comment by bdewilde** [comment]
Creating a `textacy.TextDoc` automatically runs spaCy's models over the input text, and the resulting spaCy doc is saved as an attribute: `.spacy_doc`. It's generally preferred that you just call the `TextDoc.named_entities()` method, but you could also pass in a spaCy doc directly. You could also create a spaCy doc via spaCy itself, but textacy is intended as a user-friendly, higher-level interface around it, so that would be a bit strange. Here are your options:

```
import spacy
import textacy

text = "Donald Trump is running for president. Hillary Clinton is, too."

doc = textacy.TextDoc(text)
nes1 = list(doc.named_entities())
nes2 = list(textacy.extract.named_entities(doc.spacy_doc))

nlp = spacy.load('en')
spacy_doc = nlp(text)
nes3 = list(textacy.extract.named_entities(spacy_doc))

assert nes1 == nes2 == nes3
```

**Comment by cmuell89** [comment]
@bdewilde 

Does textacy load an instance of Spacy (space.load('en')) each time for method calls such as textacy.TextDoc(text) or do you maintain a single instance of it? Latency in loading the 'en' model can be an issue if you want to repeatedly call these sorts of methods on small documents (chats and/or queries).

I've used SpaCy as a singleton in my prototyping since it takes about 15-20 seconds to load the model on my machine.

Just curious.

Carl

**Comment by bdewilde** [comment]
`textacy` only loads a given spaCy model once then caches the result, for exactly the reason you mention. You can see this in the `data.py` module if you're curious.

**Comment by adrianR2** [comment]
I pasted the code, and still does not work due to TextDoc:
```
C:\Anaconda2\Lib\site-packages\textacy\textacy-0.2.3>python
Python 2.7.11 |Anaconda 4.0.0 (32-bit)| (default, Mar  4 2016, 15:18:41) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import spacy
>>> import textacy
C:\Anaconda2\lib\site-packages\fuzzywuzzy-0.10.0-py2.7.egg\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this war
ning
>>> text = "Donald Trump is running for president. Hillary Clinton is, too."
>>> doc = textacy.TextDoc(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textacy\texts.py", line 77, in __init__
    raise ValueError(msg)
ValueError: TextDoc must be initialized with set([<type 'spacy.tokens.doc.Doc'>, <type 'unicode'>]), not <type 'str'>
>>>
```

**Comment by bdewilde** [comment]
@adrianR2 Read the error message, read the docs. You're passing in a bytes str (Python 2's default), but it requires a unicode str (Python 3's default). I wrote my example code in Python 3 so didn't have to specify `text = unicode("Donald Trump is running for president. Hillary Clinton is, too.")`.

**Comment by adrianR2** [comment]
Thank you!
