### ISSUE TITLE
scikit-learn > 0.24

### ISSUE THREAD

**Issue by fabaff** [chartbeat-labs/textacy#319]
[cikit-learn 0.24.1](https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_0_24_0.html) was released a while ago. 

https://github.com/chartbeat-labs/textacy/blob/cdedd2351bf2a56e8773ec162e08c3188809d486/setup.cfg#L51

The Nix packages is already at 0.24.1 and this [breaks the build](https://github.com/NixOS/nixpkgs/pull/114743).

Do you have any plans to allow scikit-learn > 0.24?

Thanks

**Comment by bdewilde** [comment]
Hi @fabaff , I've started updating textacy to work with spacy v3 (on the `develop` branch), and plan to allow for newer scikit-learn there. It's not trivial, since in the current setup I have to train a new language identification model using sklearn v0.24 before textacy will work with it. Will let you know here when it's good to go.

**Comment by bdewilde** [comment]
Hi again, just following up to confirm that this version cap has been removed on the `develop` branch, and everything seems to be working fine with the latest version of `scikit-learn`. I won't close this issue out until the fix is released, but please feel free to checkout the dev branch in the meantime.

**Comment by bdewilde** [comment]
Update: this has been resolved as of today's v0.11 release: https://github.com/chartbeat-labs/textacy/releases/tag/0.11.0
