### ISSUE TITLE
 No module named 'textacy.corpora'

### ISSUE THREAD

**Issue by masterchop** [chartbeat-labs/textacy#338]
### steps to reproduce

1. do this
>>> import textacy
>>> from textacy.corpora.wiki_reader import WikiReader

### expected vs. actual behavior
i want to work with wikipedia dump.

### possible solution?
N/A

### context
import the library.

### environment

- operating system:
- python version: Python 3.6.9
- `spacy` version:  2.3.5
- installed `spacy` models: en
- `textacy` version: 0.10.1

**Comment by bdewilde** [comment]
Hi @masterchop , there hasn't been a `corpora` subpackage since v0.4 (see [changelog](https://github.com/chartbeat-labs/textacy/blob/master/CHANGES.md#040-2017-06-21)). I think what you want is

```python
import textacy.datasets
wiki = textacy.datasets.Wikipedia()
```

Here are the API docs for v0.10.1: https://textacy.readthedocs.io/en/0.10.1/api_reference/datasets.html#textacy.datasets.wikimedia.Wikipedia

**Comment by masterchop** [comment]
I knew it was something like that as I was not able to find it in source but also there isn't much about that change on the internet hehe thanks
