### ISSUE TITLE
exporting corpus to conllu?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [chartbeat-labs/textacy#340]
### context
I have wanted to export a spacy corpus as a conll file and it seems like this functionality has been present in the package. However, when looking at the code (as well as the documentation) I could not find any reference to the `doc_to_conll` as noted in this [stackoverflow](https://stackoverflow.com/questions/57465128/how-to-generate-conllu-from-a-doc-object).

### proposed solution

It seems like the solution has been present, but probably been removed. A solution would be to bring it back or maybe even a reference to the latest version of it then I can try to update it potentially in a PR. 

### alternative solutions?

I have examined other spacy extensions. Including the spacy-conll which sadly isn't updated for spacy v3

**Comment by bdewilde** [comment]
Hi @KennethEnevoldsen , sorry to leave you hanging! I did indeed remove that `doc_to_conll()` function in the latest release, since it was an implicit external dependency (w/ CoNLL-U) that I wasn't monitoring or maintaining. However, you can still find the original code here: https://github.com/chartbeat-labs/textacy/blob/0.10.1/src/textacy/export.py#L81-L132

I don't know if it works for your use case, but I hope it helps!

**Comment by bdewilde** [comment]
By the way, coincidentally, `spacy-conll` just published a new release compatible with spacy v3: https://github.com/BramVanroy/spacy_conll/releases/tag/v3.0.0

**Comment by KennethEnevoldsen** [comment]
Oh, wonderful. Thanks for notifying me of this!
