### ISSUE TITLE
TextDoc.as_terms_list has not implemented the dedupe flag

### ISSUE THREAD

**Issue by xumx** [chartbeat-labs/textacy#43]
## Expected Behavior
Expected term list to be deduplicated  

## Current Behavior
term list has duplicates  

## Possible Solution
deduplicate all_terms before return
`list(set(all_terms))`

**Comment by bdewilde** [comment]
Hi @xumx, the purpose of `.as_terms_list` is to convert a document into a sequence of words, ngrams, and/or named entities, the same number of times that they occur in the document. This is useful when, say, getting frequencies for all of these terms. De-duplication occurs between words/ngrams and named entities: We don't want to double-count the same instance of a given token or token span, but we do want to count it if it occurs multiple times in a document. Does that make sense?

This is expected behavior, but I didn't make it sufficiently clear in the documentation. I'll fix that. There's also a new release coming out very soon that changes this method a bit, for instance dropping the dedupe parameter that was causing confusion.
