### ISSUE TITLE
How to add stopwords?

### ISSUE THREAD

**Issue by snarb** [chartbeat-labs/textacy#60]
>>> import spacy
>>> nlp = spacy.load("en")
>>> nlp.vocab["the"].is_stop = False
>>> nlp.vocab["definitelynotastopword"].is_stop = True
>>> sentence = nlp("the word is definitelynotastopword")
>>> sentence[0].is_stop
False
>>>

>>> doc = textacy.Doc("the word is definitelynotastopword", nlp)
>>> doc[0].is_stop
True

This works for spacy but not for textacy.

**Comment by bdewilde** [comment]
Hi @snarb , you appear to be passing the `nlp` object in as the `metadata` param rather than the `lang` param, since the call is `Doc.__init__(self, content, metadata=None, lang=None)`. In the absence of `lang`, `textacy` instead detects the language of the text and loads the appropriate spacy language data — which is not the same as the `nlp` object that you've modified. Here's the correct code:

```
In [12]: doc = textacy.Doc("the word is definitelynotastopword", lang=nlp)
In [13]: doc[0].is_stop
Out[13]: False
```
