### ISSUE TITLE
fuzzywuzzy is GPL

### ISSUE THREAD

**Issue by matthayes** [chartbeat-labs/textacy#62]
I noticed that fuzzywuzzy, which textacy depends on, is licensed under GPL. Any chance textacy can migrate off of this? It seems this would be an issue for anyone who wants to use textacy but also wants to avoid using GPL.

**Comment by bdewilde** [comment]
Hi @matthayes , thanks for the heads-up. To be totally frank, I've never really understood how the various licenses (don't) work together. I'm not using `fuzzywuzzy` for anything particularly fancy — just the `token_sort_ratio`, IIRC — so maybe it wouldn't be too much trouble to move off it. Will keep you posted.

**Comment by bdewilde** [comment]
Update: It was straightforward to implement my own "token sort ratio" function, and given the narrower scope of usage than all of `fuzzywuzzy`'s, I was able to make it run faster. :raised_hands:

I made one notable change: I force all string inputs to unicode rather than ascii. So for languages with non-ascii characters, there will be differences in the resulting scores. For example:

```
>>> fuzzywuzzy.fuzz.token_sort_ratio('está bien', 'esta bien')
94
>>> textacy_token_sort_ratio('está bien', 'esta bien')
89
```

My function differentiates between "está" (is) and "esta" (this). I realize that distinction isn't necessarily intended in informal writing, but I don't think it's _incorrect_ from a string similarity perspective. Meanwhile, `fuzzywuzzy` actually drops the "á" on "está" before comparing, which seems... dicey.

I'll get this into `master` soon and let you know when I've dropped the `fuzzywuzzy` dep.
