### ISSUE TITLE
SGRank method tests observed and expected values make no sense

### ISSUE THREAD

**Issue by covuworie** [chartbeat-labs/textacy#74]
## Expected Behavior
Most of the expected values vs observed values in the `keyterms.sgrank` should match even though some may be different due to randomness of the results. `keyterms.textrank` and `keyterms.singlerank` at least seem to be behaving in that way.

## Current Behavior
Almost none of the expected and observed values for sgrank tests match. Take `test_sgrank` as an example where the test says:

```python
expected = [
            'new york times', 'york times jerusalem bureau chief', 'friedman',
            'president george h. w.', 'george polk award', 'pulitzer prize',
            'u.s. national book award', 'international reporting', 'beirut',
            'washington post']
```
However debugging this test I see the following values:

```python
observed = ['year', 'receive', 'win', 'coverage', 'reporting', 'write', 'end', 'be transfer', 'east', 'also win']
```

## Steps to Reproduce (for bugs)
Just debug the unit tests.

## Context
I was trying to make a code change to the `sgrank` method and then submit a pull request. I noticed this during the course of writing some tests and then had to back off as I don't understand what is going on. Once this issue is resolved I can get back to the code change. 

## Your Environment

* `textacy 0.3.3` and `spacy 1.6.0` versions:
* Python version: 3.6.0.1
* Operating system and version: Windows 7

**Comment by bdewilde** [comment]
Hey @covuworie , I see that something's gone wrong with the tests. I've made two updates to sgrank in the past couple months as well as updated spacy version+models, and one of those changes may have introduced a bug. I'll look into it when I have time, thanks for the heads-up.

**Comment by bdewilde** [comment]
Hi @covuworie , part of the problem — for me — arose from using a different spacy model than the one used to create the array of `values` in the `setUp()` method. When I removed that code and just take the current model's POS values, the tests passed. That's a relief! Given [the proliferation of spacy models](https://github.com/explosion/spacy-models), I may have to stop with these pre-computed value arrays; then again, I think they've taken steps in the latest release to make models more compatible across versions such that key symbols like POS tags will always have the same integer id. TBD...

Your issue was with the actual terms that `sgrank` returns. The terms I got weren't the same as the ones in the test, but they weren't _too_ different:

```
['new york times',
 'friedman',
 'beirut',
 'pulitzer prize',
 'international reporting',
 'year',
 'bureau',
 'press',
 'june',
 'international']
```

These are very different from the ones you listed above. I have no idea what's gone wrong on your side, but terms like "be transfer" and "also win" shouldn't even be considered, given their parts-of-speech. Could you tell me which spacy model you used to parse the text? Could you also submit a full code snippet to reproduce that result? That'll give me some clues to work from...

**Comment by covuworie** [comment]
Hi @bdewilde, thanks for taking the time to look at this. I  have looked at the issue again and think I was not running with a clean code base. I'm still new to python and learning as I go along (most of my programming in the past has been in C++, C#, even C and Fortran going back a little further). Now running the tests again I get the following results for the sgrank tests from top to bottom as they appear in the test file:

```

['new york times', 
 'friedman', 
 'pulitzer prize', 
 'beirut', 
 'international reporting', 
 'year', 
 'bureau', 
 'press', 
 'june', 
 'new york']

['new york times', 
 'friedman', 
 'pulitzer prize', 
 'beirut', 
 'international reporting']

['new york times', 
 'friedman', 
 'pulitzer prize', 
 'beirut', 
 'international reporting']

['New York Times', 
 'Friedman', 
 'Pulitzer Prize', 
 'Beirut', 
 'International Reporting']

['New York Times', 
 'Friedman', 
 'Pulitzer Prize', 
 'Beirut', 
 'International Reporting']

['new york times', 
 'friedman', 
 'beirut', 
 'pulitzer prize', 
 'international reporting']

```    

For the top test I get the same results as you, just in a different order. Do you get the same values? Some of the values are similar to what's listed in the tests and some are not. What do you think about these values? Are they ok?

**Comment by bdewilde** [comment]
Hey, belatedly: These seem about right to me. I'm going to close out this issue, but let me know if you have any more problems.
