### ISSUE TITLE
to_bag_of_terms method fails to find some expressions in document

### ISSUE THREAD

**Issue by naileakim** [chartbeat-labs/textacy#82]
Hello,

I am willing to get the total count for different expressions over a document, like this one: `serious implications`.

I am having issues with the `to_bag_of_terms` method, which doesn't find some expressions  that do exist in the document. Here is what I did so far:

```python
content = textacy.fileio.read.read_file("data/document.txt", mode=u'rt', encoding=None)
doc = textacy.Doc(content)
doc = textacy.Doc(textacy.preprocess_text(doc.text, lowercase=True, no_punct=True))
ngrams = doc.to_bag_of_terms(ngrams=(1,2,3,4,5,6,7,8,9,10), lowercase=True, as_strings=True, weighting="count")
print ngrams
```

In the resulting ngrams, the expression `serious implications` doesn't exist. However, when I run the `keyword_in_context` method:

```python
textacy.text_utils.keyword_in_context(doc.text, 'serious implications', window_width=20)
```

It returns the sentence containing the expression. I can't figure out what I'm missing. My environment config is:

```
textacy 0.3.3
spacy 1.7.3
Python 2.7.13
```

Any help is appreciated. Thanks!

**Comment by bdewilde** [comment]
Hi @naileakim , the problem you describe is odd, and I can't think of any potential causes off the top of my head. Could you provide a minimal code sample (including the text and outputs) that reproduces the problem?

**Comment by naileakim** [comment]
Sure, here is a minimal code sample that reproduces the problem. The text file associated is available [here](https://github.com/chartbeat-labs/textacy/files/923518/cs224n-2017-tensorflow-1.txt).

```python
import textacy
content = textacy.fileio.read.read_file("../data/cs224n-2017-tensorflow-1.txt", mode=u'rt', encoding=None)
doc = textacy.Doc(content)
doc = textacy.Doc(textacy.preprocess_text(doc.text, lowercase=True, no_punct=True))
ngrams = doc.to_bag_of_terms(ngrams=set(range(1, len(doc))), lowercase=True, as_strings=True, weighting="count")
```

Searching for the ngram *"one way to address the problem"* in the `ngram` dict:

```python
print ngrams['one way to address the problem']
```

 Outputs:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-31e181bf13e8> in <module>()
----> 1 print ngrams['one way to address the problem']

KeyError: 'one way to address the problem'
```

Searching for an other ngram, like *"parameters in a neural network in our example"* in the `ngram` dict seems to work:

```python
print ngrams['parameters in a neural network in our example']
```

Outputs:

```
1
```

Applying KWIC to the original ngram works fine:

```python
textacy.text_utils.keyword_in_context(doc.text, 'one way to address the problem', window_width=20)
```

Outputs:

```
different variables  one way to address the problem  is to use classes t
```

I am starting with the textacy framework, maybe I missed something?

**Comment by bdewilde** [comment]
Aha! Under the hood, `Doc.to_bag_of_terms()` uses `Doc.to_terms_list()`, and when the `ngrams` param is an int or sequence of ints, it calls `extract.ngrams()` to get the relevant n-grams. These methods allow you to specify `**kwargs` for such underlying functions, but they don't _require_ it; in the absence of extra kwargs, default values are used. In your particular case, `extract.ngrams()` is getting called with `filter_stops=True`, and as a result, ngrams starting or ending with a stopword are excluded. _That_ is why "one way to address the problem" doesn't show up.

You can easily resolve the issue by passing `filter_stops=False` to `Doc.to_bag_of_terms()`:

```
>>> ngrams = doc.to_bag_of_terms(
...    ngrams=set(range(1, len(doc))), lowercase=True, as_strings=True, weighting="count",
...    filter_stops=False)
>>> ngrams['one way to address']
1
```

All of this _is_ covered in the docstrings, but only if you go all the way down that rabbit hole. Let me see if I can make anything more obvious.

Lastly, a couple of notes beyond the issue:

- You don't need to call `textacy.Doc()` on the raw text and then again on the preprocessed text; you only need the latter.
- Instead of passing  the `lowercase=True` param, you should prefer `normalize='lower'`. The former will be deprecated in the not-too-distant future.
- You are extracting _a lot_ of ngrams. In most cases, only 2-grams, 3-grams, and maybe even 4- and 5-grams are used as features or units of interest, and I just want to make sure that you do indeed need a 594-gram (found via `max(len(ng) for ng in ngrams)`).

**Comment by naileakim** [comment]
Thanks for your help, I understand where the issue comes from now. I'll take your notes into consideration as well.

textacy is great, keep up the good work! 🙂
