### ISSUE TITLE
the generated Documentation on readthedocs site is empty

### ISSUE THREAD

**Issue by demarant** [chartbeat-labs/textacy#87]
Since yesterday the documentation at [readthedocs](http://textacy.readthedocs.io/en/latest/api_reference.html) is empty

**Comment by bdewilde** [comment]
😖  I was having trouble with readthedocs yesterday, thought I fixed it, but apparently did not. I'll figure it out ASAP, thanks for the heads-up!

**Comment by bdewilde** [comment]
Okay, so, readthedocs is logging a bizarre error that prevents it from updating the auto-generated API docs but doesn't prevent it from completing the build. I can't reproduce it locally, but that may be a blessing: If you have the `sphinx` package installed, you should be able to go into the `textacy/docs` directory on your local machine and type `make html` in order to build the docs yourself. It's a temporary workaround, if you need these docs before I can figure out what the hell readthedocs is doing.

**Comment by demarant** [comment]
@bdewilde I will build locally in the meantime as you suggested. Thanks for your great work!

**Comment by bdewilde** [comment]
Hey @demarant , I got it to work: the API docs are back up [here](https://textacy.readthedocs.io/en/latest/api_reference.html). Note: You may have to do a hard refresh on the page to get rid of an out-of-date cached version.

For reasons unknown, readthedocs was mishandling my usage of Python's stdlib `pkgutil` in the `__init__.py` file, and that caused the sphinx autodocs to fail. I replaced it by an equivalent using `os.path` that is, in my opinion, _worse_ but not incorrect. ¯\_(ツ)_/¯
