### ISSUE TITLE
Textacy assuming 4 cpu cores are available

### ISSUE THREAD

**Issue by AbdealiJK** [chartbeat-labs/textacy#89]
Textacy not using all my threads for creating a corpus efficiently

## Expected Behavior
When I create a Corpus in textacy, I would have assumed it would use all my CPU resources available. I have a machine with 26 CPU cores, and textacy doesn't use up all the threads by default.

## Current Behavior
Spacy assumed it should use only 4 cpus.

## Possible Solution
The general recommendation is to use nproc - 1 number of threads to avoid clashing with the OS processes and also using the most CPU resources available on the machine.
In python, nproc can be found using `multiprocessing.cpu_count()`

**Comment by bdewilde** [comment]
Hi @AbdealiJK , I assume that you're building a corpus by calling `Corpus.add_texts()`, since that is the only place where spacy's `Language.pipe()` is used. You may specify the number of threads to use via the `n_threads` parameter; the default value is 4, but you may set it to 26 – 1 if you wish to do so.

If I've misunderstood your problem, please 1. reopen this issue and 2. provide more details.

**Comment by AbdealiJK** [comment]
That's exactly what I am doing now, but before I realized this, I was using the `Corpus` constructure to pass my texts to the Corpus. When I did that, there was no option to specify num_threads and I assumed it would use all until I found out it does not.

Hence, while I can set the thread number, I think the default value should be `nproc - 1` to make it simpler for users
