### ISSUE TITLE
List of Docs to Corpus? More straight forward than "streams"?

### ISSUE THREAD

**Issue by terratenney** [chartbeat-labs/textacy#96]
Totally agree using content streams for corpus building is more efficient, but is there a way to build a corpus out of a list of textacy docs? Since they all have lang, content (text), and metadata.

Maybe I am missing something in the code, I am still rather new to the library . 

Thanks.

**Comment by bdewilde** [comment]
Hey @terratenney , there's no dedicated `Corpus` method for adding a list of `Doc`s, since there's very little performance advantage over straightforward iteration:

```
for doc in docs:
    corpus.add_doc(doc)
```

One thing to note: The spacy language instance used to parse every `Doc` must be the same as the one used to initialize the `Corpus`, otherwise a `ValueError` will be raised.

Feel free to re-open if I've misunderstood your issue.
