### ISSUE TITLE
Add custom stop_word list?

### ISSUE THREAD

**Issue by terratenney** [chartbeat-labs/textacy#97]
Add custom stop_word set to (I assume) spacy.en.stopwords? Or, it there another stop word filtering for method textacy? Tried to follow advice here: https://github.com/explosion/spaCy/issues/226

**Comment by bdewilde** [comment]
Hi @terratenney , I consider this out-of-scope for `textacy` — and definitely in `spacy`'s wheelhouse. The goal is to build on and extend the functionality implemented in `spacy`, not to re-implement it. I encourage you to ping Matt and Ines on [their github repo](https://github.com/explosion/spaCy), they're very responsive.

**Comment by FelixLC** [comment]
@bdewilde I think what @terratenney wanted, was how to use spacy's method for using custom stop words, in the context of textacy.

Doing the following:

```
for word in en.STOPWORDS:
    lexeme = nlp.vocab[word]
    lexeme.is_stop = True
```

has no effect on textacy, even if it was loaded after this piece of code.

**Comment by bdewilde** [comment]
Hi @FelixLC , `textacy` uses `spacy`'s processing pipelines, vocab, etc. as-is, so if you modify one of those, it's all the same to `textacy`. Could you provide a full code example to illustrate the issue?

**Comment by FelixLC** [comment]
@bdewilde sure !
Let's say i want to banish 2 letter words from STOP_WORDS in the french model, i.e. all words that are less than 2 letter long should not be stop words. In https://github.com/explosion/spaCy/issues/226, spacy recommends to do:

```python
import spacy
nlp = spacy.load('fr')
for word in spacy.fr.STOP_WORDS:
    lexeme = nlp.vocab[word]
    lexeme.is_stop = False if len(word) <= 2 else True

for w in nlp("le pigeon sur la branche"):
    print(w.text, w.is_stop)
```

we get :

```
le False
pigeon False
sur True
la False
branche False
```
which is good, since `le` and `la` have been ignored, although they were previously stop words

But then, if I load textacy and try to get a filtered terms list:

```python
import textacy
textacy.doc.Doc("le pigeon sur la branche", lang='fr').to_bag_of_terms(
                ngrams=(1, 2), normalize=False, as_strings=True, filter_stops=True, filter_nums=True, filter_punct=True)
```
yields `{'branche': 1, 'pigeon': 1}`

however, an easy workaround that i just found is to ask spacy to process the text

```python
import textacy
textacy.doc.Doc(nlp("le pigeon sur la branche"), lang='fr').to_bag_of_terms(
                ngrams=(1, 2), normalize=False, as_strings=True, filter_stops=True, filter_nums=True, filter_punct=True)
```
... which yields `{'branche': 1, 'la': 1, 'la branche': 1, 'le': 1, 'le pigeon': 1, 'pigeon': 1}`
{'branche': 1, 'pigeon': 1}

**Comment by bdewilde** [comment]
Aha. The issue is that instantiating a `textacy.Doc(text, lang='fr')` uses a new and _unmodified_ instance of spacy's French language pipeline to process the text. You need to tell textacy to use something "non-standard".

Fortunately, there's a very easy way to handle this: Just pass the modified pipeline in for the lang param, i.e. `textacy.Doc(text, lang=nlp)`, where `nlp` is the instance you modified in your post. Sound good?
